<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>no.lyse.plattform</groupId>
    <artifactId>oauth2-playground</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <description>OAuth2 Playground</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <spring.version>3.1.3</spring.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.plugin.validation>VERBOSE</maven.plugin.validation>
        <!--docker.image.registry>localhost:5000</docker.image.registry-->
        <!--spring-boot.build-image.publish>true</spring-boot.build-image.publish-->
        <!--spring-boot.build-image.imageName>${docker.image.registry}/${project.groupId}/${project.artifactId}:${project.version}</spring-boot.build-image.imageName-->
        <maven.deploy.skip>true</maven.deploy.skip> <!-- skip maven deploy in favor of docker push -->
        <artifacts.server>acrlypfelles.azurecr.io</artifacts.server>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>${spring.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <defaultGoal>verify</defaultGoal>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.3.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.3.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.1.2</version>
                </plugin>
                <plugin><groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>3.1.2</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>3.6.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.12.1</version>
                </plugin>
                <plugin>
                    <groupId>org.openapitools</groupId>
                    <artifactId>openapi-generator-maven-plugin</artifactId>
                    <version>7.0.0-beta</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>3.4.0</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.amashchenko.maven.plugin</groupId>
                <artifactId>gitflow-maven-plugin</artifactId>
                <version>1.19.0</version>
                <configuration>
                    <pushRemote>true</pushRemote>
                    <!-- we use major.minor.patch versioning, being 0.1.2 respectively.
                          By default the minor version is increased.
                          Hotfixes increase the patch version. -->
                    <!--suppress UnresolvedMavenProperty -->
                    <versionDigitToIncrement>${gitflowDigitToIncrement}</versionDigitToIncrement>

                    <gitFlowConfig>
                        <productionBranch>main</productionBranch>
                        <developmentBranch>develop</developmentBranch>
                    </gitFlowConfig>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <modules>
        <module>authorization-server</module>
        <module>resource-server</module>
        <module>client-app</module>
        <module>quotes-api</module>
        <module>e2e-tests</module>
        <module>healthcheck-client</module>
    </modules>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>Lyse Github Packages</name>
            <url>https://maven.pkg.github.com/Lyse-AS/oauth2-playground</url>
        </repository>
        <snapshotRepository>
            <id>github</id>
            <name>Lyse Github Packages</name>
            <url>https://maven.pkg.github.com/Lyse-AS/oauth2-playground</url>
            <uniqueVersion>false</uniqueVersion>
        </snapshotRepository>
    </distributionManagement>

    <repositories>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/Lyse-AS/oauth2-playground</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <profiles>
        <profile>
            <id>docker-compose</id>
            <activation>
                <property>
                    <name>env.RUNTIME_ENVIRONMENT</name>
                    <value>docker</value>
                </property>
            </activation>
            <properties>
                <spring-boot.build-image.skip>true</spring-boot.build-image.skip>
            </properties>
            <!--build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <id>install playwright browser</id>
                                <goals><goal>java</goal></goals>
                                <phase>pre-integration-test</phase>
                                <configuration>
                                    <mainClass>com.microsoft.playwright.CLI</mainClass>
                                    <arguments>
                                        <argument>install-deps</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>


                    </plugin>
                </plugins>
            </build-->
            <modules>
                <module>e2e-tests</module>
            </modules>
        </profile>
    </profiles>
</project>
