<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>no.lyse.plattform</groupId>
        <artifactId>oauth2-playground</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>
    <groupId>no.lyse.plattform.oauth2-playground</groupId>
    <artifactId>quotes-api</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <resources>
            <resource>
                <directory>${pom.basedir}/src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <skip>true</skip>
                            <inputSpec>${project.build.outputDirectory}/quotes-api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <ignoreFileOverride>${project.basedir}/.openapi-generator-ignore</ignoreFileOverride>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <apiPackage>no.lyse.plattform.oauth2playground.quotesapi.api</apiPackage>
                            <modelPackage>no.lyse.plattform.oauth2playground.quotesapi.model</modelPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <reactive>true</reactive>
                                <documentationProvider>source</documentationProvider>
                                <!--annotationLibrary>none</annotationLibrary-->
                                <requestMappingMode>none</requestMappingMode>
                                <useSpringController>false</useSpringController>
                                <useSpringBoot3>true</useSpringBoot3>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <skipDefaultInterface>true</skipDefaultInterface>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-openapi</id>
                        <goals><goal>attach-artifact</goal></goals>
                        <phase>package</phase>
                        <configuration>
                            <artifacts>
                                <artifact>
                                    <file>${project.build.outputDirectory}/quotes-api.yaml</file>
                                    <type>yaml</type>
                                    <classifier>openapi</classifier>
                                </artifact>
                            </artifacts>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
