<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>no.lyse.plattform</groupId>
        <artifactId>oauth2-playground</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>
    <groupId>no.lyse.plattform.oauth2-playground</groupId>
    <artifactId>resource-server</artifactId>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-oauth2-authorization-server</artifactId>
                <version>1.0.1</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <dependency>
            <groupId>no.lyse.plattform.oauth2-playground</groupId>
            <artifactId>quotes-api</artifactId>
            <version>${project.version}</version>
            <classifier>openapi</classifier>
            <type>yaml</type>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-starter-active-directory</artifactId>
            <version>5.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <!--suppress UnresolvedMavenProperty -->
                        <name>${artifacts.server}/${project.artifactId}:${project.version}</name>
                        <!--publish>${acr.publish}</publish-->
                        <env>
                            <BP_JVM_TYPE>JDK</BP_JVM_TYPE>
                        </env>
                    </image>
                    <docker>
                        <publishRegistry>
                            <!--suppress UnresolvedMavenProperty -->
                            <token>${env.ACR_TOKEN}</token>
                        </publishRegistry>
                    </docker>
                </configuration>
                <executions>
                    <execution>
                        <id>executable-jar</id>
                        <goals>
                            <goal>build-info</goal>
                            <goal>repackage</goal>
                            <goal>build-image</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-openapi</id>
                        <phase>generate-resources</phase>
                        <goals><goal>copy-dependencies</goal></goals>
                        <configuration>
                            <includeClassifiers>openapi</includeClassifiers>
                            <includeTypes>yaml</includeTypes>
                            <stripVersion>true</stripVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <inputSpec>${project.build.directory}/dependency/quotes-api-openapi.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <apiPackage>no.lyse.plattform.oauth2playground.quotesapi.api</apiPackage>
                            <modelPackage>no.lyse.plattform.oauth2playground.quotesapi.model</modelPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <reactive>true</reactive>
                                <documentationProvider>source</documentationProvider>
                                <!--annotationLibrary>none</annotationLibrary-->
                                <requestMappingMode>none</requestMappingMode>
                                <useSpringController>false</useSpringController>
                                <useSpringBoot3>true</useSpringBoot3>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <openApiNullable>false</openApiNullable>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
