apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
  namespace: reference-implementation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: client-app
          image: acrlypfelles.azurecr.io/no.lyse.plattform.oauth2-playground.client-app:2.0.0-SNAPSHOT
          args:
            - --spring.profiles.active=azure,dev
            - --spring.security.oauth2.client.provider.spring.issuer-uri=https://login.microsoftonline.com/22ca942f-06c2-4f38-9407-0e447dedbb67/v2.0
            - --server.port=8080
            - --messages.base-uri=http://resource-server.dev.privatelink.westeurope.azmk8s.io
            - --spring.security.oauth2.client.registration.messaging-client-oidc.redirect-uri=http://client-app.dev.privatelink.westeurope.azmk8s.io/login/oauth2/code/{registrationId}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '1'
              memory: 1G
            limits:
              memory: 1G