management:
  httpexchanges:
    recording: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://idp:9000/realms/lyse-tele/
          client-id: messaging-client
debug: true
server:
  port: 8090
