
server:
  port: 9000

debug: false
logging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.web: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          messaging-client:
            registration:
              client-id: "messaging-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/messaging-client-oidc"
                - "http://localhost:8080/login/oauth2/code/messaging-client-authorization-code"
                - "http://localhost:8080/authorized"
                - "http://client-app:8080/login/oauth2/code/messaging-client-oidc"
                - "http://client-app:8080/login/oauth2/code/messaging-client-authorization-code"
                - "http://client-app:8080/authorized"
                - "http://localhost:3000/login/oauth2/code/messaging-client-oidc"
                - "http://localhost:3000/login/oauth2/code/messaging-client-authorization-code"
                - "http://localhost:3000/authorized"
              post-logout-redirect-uris:
                - "http://client-app:8080/"
              scopes:
                - "openid"
                - "profile"
                - "message.read"
                - "message.write"
            require-authorization-consent: true
  http:
    codecs:
      log-request-details: true

auth-server:
  issuer: 'http://idp:9000'
  users:
    - username: "user1"
      password: "{noop}password"
      roles:
        - "USER"
