apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: aa203dd7-41ac-454c-92d1-d6daf4b009a0
  labels:
    azure.workload.identity/use: "true"
  name: id-lyp-refimp-dev
  namespace: reference-implementation
