<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>no.lyse.plattform</groupId>
        <artifactId>oauth2-playground</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>
    <groupId>no.lyse.plattform.oauth2-playground</groupId>
    <artifactId>client-app</artifactId>

    <properties>
        <npm.skip>false</npm.skip>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.nimbusds</groupId>
                <artifactId>nimbus-jose-jwt</artifactId>
                <version>${nimbus.jose.jwt.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-core</artifactId>
        </dependency>
        <dependency>
            <groupId>no.lyse.plattform.oauth2-playground</groupId>
            <artifactId>quotes-api</artifactId>
            <version>${project.version}</version>
            <type>yaml</type>
            <classifier>openapi</classifier>
        </dependency>

        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>webjars-locator-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>bootstrap</artifactId>
            <version>5.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>jquery</artifactId>
            <version>3.7.1</version>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <!--suppress UnresolvedMavenProperty -->
                        <name>${artifacts.server}/${project.groupId}.${project.artifactId}:${project.version}</name>
                        <publish>${acr.publish}</publish>
                        <builder>paketobuildpacks/builder-jammy-base</builder>
                        <env>
                            <BP_JVM_TYPE>JDK</BP_JVM_TYPE>
                            <BP_JVM_VERSION>${maven.compiler.target}</BP_JVM_VERSION>
                        </env>
                    </image>
                    <docker>
                        <publishRegistry>
                            <!--suppress UnresolvedMavenProperty -->
                            <token>${env.ACR_TOKEN}</token>
                        </publishRegistry>
                    </docker>
                </configuration>
                <executions>
                    <execution>
                        <id>build-image</id>
                        <goals>
                            <goal>build-info</goal>
                            <goal>repackage</goal>
                            <goal>build-image</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.13.2</version>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>i -E</arguments>
                        </configuration>
                        <phase>generate-resources</phase>
                    </execution>
                    <execution>
                        <id>npm run build</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <arguments>run build</arguments>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <workingDirectory>${project.basedir}/frontend</workingDirectory>
                    <nodeVersion>v18.16.1</nodeVersion>
                    <npmVersion>9.5.1</npmVersion>
                    <!--installDirectory>${project.basedir}/frontend/build</installDirectory-->
                    <skip>${npm.skip}</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-openapi</id>
                        <phase>generate-resources</phase>
                        <goals><goal>copy-dependencies</goal></goals>
                        <configuration>
                            <includeClassifiers>openapi</includeClassifiers>
                            <includeTypes>yaml</includeTypes>
                            <stripVersion>true</stripVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <!-- support for client code generation for spring 6 and reactive is really poor, we just generate the model -->
                            <inputSpec>${project.build.directory}/dependency/quotes-api-openapi.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateModelTests>false</generateModelTests>
                            <modelPackage>no.lyse.plattform.oauth2playground.quotesapi.model</modelPackage>
                            <configOptions>
                                <annotationLibrary>none</annotationLibrary>
                                <library>native</library>
                                <useJakartaEe>true</useJakartaEe>
                            </configOptions>
                            <globalProperties>
                            </globalProperties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>
