
name: Release
on:
  workflow_dispatch:
    inputs:
      buildtype:
        description: 'Build type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

  pull_request:
    types:
      - closed


concurrency: release

jobs:
  release:
    if: github.ref == 'refs/heads/develop' || contains(toJSON(github.head_ref), 'release/')
    runs-on: ltedev
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/login@v1
        name: 'Az CLI login'
        with:
          creds: ${{ secrets.AZ_SPN_LYP_ACRPUSH }}
      - name: 'Fetch ACR Token'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo ACR_TOKEN=$(az acr login --name acrlypfelles --expose-token | jq -r .accessToken) >> $GITHUB_ENV
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # cache: 'maven'
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Generate versions'
        id: version
        uses: 'Lyse-AS/lyse-version-action@develop'
        with:
          increment: ${{ inputs.buildtype }}
          project-type: maven

      - name: gitflow-workflow-action release workflows
        uses: Lyse-AS/lt-gitflow-workflow-action@0.0.103
        with:
          develop_branch: "develop"
          main_branch: "main"
          version: ${{ steps.version.outputs.new-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Deploy release
        run: |
          git switch main
          mvn -B deploy -Dacr.publish=true
        env:
          GITHUB_TOKEN: ${{ github.token }}
